# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museos', '0024_auto_20180512_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='museum',
            old_name='accessibility',
            new_name='ACCESIBILIDAD',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='description',
            new_name='BARRIO',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='tlfn',
            new_name='CODIGO_POSTAL',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='postal_code',
            new_name='CONTENT_URL',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='province',
            new_name='DESCRIPCION',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='museum',
            old_name='fax',
            new_name='LOCALIDAD',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='location',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='name',
        ),
        migrations.AddField(
            model_name='museum',
            name='COORDENADA_X',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='COORDENADA_Y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='DESCRIPCION_ENTIDAD',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='DISTRITO',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='FAX',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='HORARIO',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='LATITUD',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='LONGITUD',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='NOMBRE',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='NOMBRE_VIA',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='NUM',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='PK',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='PROVINCIA',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='TELEFONO',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='TIPO',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='museum',
            name='TRANSPORTE',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
